### ISSUE TITLE
Is there a reason for why some AST nodes are not public?

### ISSUE THREAD

**Issue by peteruhnak** [jkuhnert/ognl#102]
Is there a reason for why some AST nodes are not public?

E.g.`ASTEq`, `ASTAdd` are private
but e.g. `ASTChain`, `ASTCtor`, `ASTProperty` are public.

This makes it impossible to create a visitor, unless I put it into `ognl` package itself.

**Comment by lukaszlenart** [comment]
I have no idea tbh, maybe @jkuhnert will shed some lights

**Comment by jkuhnert** [comment]
I think all or most of those are / were automatically generated from the grammar file. Is my vague recollection without digging into code for proof / history.

**Comment by peteruhnak** [comment]
Cool, so there would be no objection to me making them all public?

**Comment by lukaszlenart** [comment]
Sure, why not.
