### ISSUE TITLE
IllegalArgumentException when calling Ognl.getValue(Object, Object, Class)

### ISSUE THREAD

**Issue by arachne-digital** [jkuhnert/ognl#105]
Tested with 3.2.14.

Calling `Ognl.getValue(Object, Object, Class)` calls `Ognl.createDefaultContext(Object)` (which is marked as deprecated). This then calls constructor `OgnlContext(ClassResolver, TypeConverter, MemberAccess)` with all `null` arguments, which finally calls the other constructor `OgnlContext(MemberAccess, ClassResolver, TypeConverter, Map)` which throws `IllegalArgumentException("MemberAccess implementation must be provided - null not permitted!")`.

I'm not sure whether the internal use of a deprecated call is a bug (deprecated is not supposed to mean _broken_, after all), or whether further overloads of `Ognl.getValue` (I'm actually calling `Ognl.getValue(String, Object)` which calls `Ognl.getValue(String, Object, Class)`, which calls `Ognl.getValue(Object, Object, Class)`) ought to have been deprecated (although ditto), or whether something else is amiss, but there is clearly an issue here.

The issue was introduced in version 3.2.2, in commit e30b2112979d1be7bed8073f1f47bffed6277fb2

**Comment by lukaszlenart** [comment]
I thought about this and the only idea I have is to create an instance of `MemberAccess` on-flight with accepting accessing public methods only, wdyt?
