### ISSUE TITLE
Should this null-check be here?

### ISSUE THREAD

**Issue by ZainlessBrombie** [jkuhnert/ognl#111]
https://github.com/jkuhnert/ognl/blob/99d53aebe43436e90351ee64c99ec1eb7b675204/src/main/java/ognl/OgnlRuntime.java#L1951

I'm passing in some nulls in my varargs, which is legal. However they are being filtered out here. Is this intentional? This does not seem correct to me.
A single null would be ambiguous because it could be meant to be the array OR the array content, but multiple nulls are always interpreted as an array in java varargs.

**Comment by lukaszlenart** [comment]
Hm... looks like you are right

**Comment by lukaszlenart** [comment]
It's ok, see #113
