### ISSUE TITLE
Varargs method not found if no varargs are given

### ISSUE THREAD

**Issue by ZainlessBrombie** [jkuhnert/ognl#112]
I have a method 
```java
interface Accessible {
        default Accessible access(Object... args) {
            return /* whatever */;
        }
}
```
When calling access() without arguments, a java.lang.NoSuchMethodException is thrown because the varargs method is not found.

**Comment by lukaszlenart** [comment]
Could you add a more complex example? Or even a test case?

**Comment by ZainlessBrombie** [comment]
Sure.
In MethodTest.java the following test case shows the issue:
```java
{ "isThisVarArgsWorking()", Boolean.TRUE },
```

PS: Also found this in MethodTest.java:
```java
// TODO This one doesn't work - even 'toArray(new String[0]) returns Object[] and so the wrong method is called - currently no idea how to handle this...
{ "testMethods.showList(testMethods.getStringList().toArray(new String[0]))", ROOT.getTestMethods().showList(ROOT.getTestMethods().getStringList().toArray(new String[0])) },
```
This is not correct, it does not return `Object[]`, it returns `String[]{"Hello", "World"}` correctly. However, since toArray is generic its head shows the return type to be Object[], not String[]. This causes ognl to resolve the `showList(Object[] args)` method, not its overload of `showList(String[] args)`, which javac figures out. `showList(Object[] args)` always returns "Objects" regardless of array component type, so the test fails. The problem then is one of array generics, not an incorrect Array type being instanciated.

:)
