### ISSUE TITLE
OGNL issues with java 16 and 17

### ISSUE THREAD

**Issue by RicardoDias19** [jkuhnert/ognl#152]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ognl.OgnlRuntime (file:XXXXXXXXXXXXXXXXXXXXXX/WEB-INF/lib/ognl-3.0.21.jar) to method java.util.HashMap$Node.getValue()
WARNING: Please consider reporting this to the maintainers of ognl.OgnlRuntime
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This warning message happens while I was running java 15. But since java 16 on wards struts-jquery-chart-tags stop working because they rely on ognl to assign dynamic data value. Access operation to to method java.util.HashMap$Node.getValue() is denied.

Is there any solution or idea? 

I am running ognl 3.2.1. 
Higher releases shows us the error below:
java.lang.NoClassDefFoundError: ognl/DefaultMemberAccess

**Comment by lukaszlenart** [comment]
Just to clarify, your error message on the top shows `ognl-3.0.21.jar` which means you are using OGNL 3.0.21 (an very old version). Are you sure you are running OGNL 3.2.1?

I would suggest switching to the latest version [3.3.2](https://github.com/jkuhnert/ognl/blob/master/docs/VersionNotes.md#release-notes---version-332-2022-01-09) which should address the problem -> #144 - also the problem with missing `DefaultMemberAccess` has been resolved in [3.2.19](https://github.com/jkuhnert/ognl/blob/master/docs/VersionNotes.md#release-notes---version-3219-2021-03-18).

**Comment by RicardoDias19** [comment]
Hi, Lukazlenart,

Yes, I am running ognl 3.2.1. And I tried 3.3.2 version... I read in a forum that DefaultMemberAccess was removed before 3.2.1 version. That is why I downgraded from 3.3.2 to 3.2.1.

The warning message while running versions 3.2.1 and 3.0.21 is the same using java 15. The reason it display 3.0.21 in the message is because I copied the message to report to you while running 3.0.21. I upgraded it later but I did not copy the message again.

But here is the message while running it with java 15:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ognl.OgnlRuntime (file:/C:/Users/xxxx/WEB-INF/lib/ognl-3.2.1.jar) to method java.util.HashMap$Node.getValue()
WARNING: Please consider reporting this to the maintainers of ognl.OgnlRuntime
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by lukaszlenart** [comment]
What version of Struts do you use?

**Comment by RicardoDias19** [comment]
I´m using struts2-core 2.5.29

**Comment by lukaszlenart** [comment]
I think you must wait for incoming Struts 6.0 (aka Struts 2.6) where a proper support for the latest Java has been already implemented.
https://cwiki.apache.org/confluence/display/WW/Struts+2.5+to+6.0.0+migration

**Comment by RicardoDias19** [comment]
That is good.
Is there any release date yet?

**Comment by lukaszlenart** [comment]
It should be soon, in 2-4 weeks

**Comment by RicardoDias19** [comment]
Thank you, Lukas. GJ.

**Comment by lukaszlenart** [comment]
Struts 6.0.0 is out
