### ISSUE TITLE
TypeConverter / OgnlOps 'double boxing'

### ISSUE THREAD

**Issue by sa-ChristianNiessner** [jkuhnert/ognl#25]
Hi,

I just pushed a new branch that also addresses another 'inconsistency' issue I was fighting in the past:
The automatic Type-Conversion puts a List (or Collection) into an array by doing new Object[] { <listclass> } instead of using the items of the list for the array. I think this would be the more desired behaviour. I also fixed the related unit tests from #16 / #19 respectively and added some new tests.

The commit [410dee5f64410f98ad4171150dc19869abd7de4c](https://github.com/secadm/ognl/commit/410dee5f64410f98ad4171150dc19869abd7de4c] (branch [TypeConverterDoubleArrayBoxing](https://github.com/secadm/ognl/commits/TypeConverterDoubleArrayBoxing)) addresses the issue.

This patch is based on #23 / #24 and so i'll create a pull request after #24 ist merged or the pull request will also provide #24. But maybe both requests can be reviewed together.

Bye,
    Chris

**Comment by lukaszlenart** [comment]
Great! I would rather push a new version based on #24 and then merge this one (and push new release), it's a safer path :)

**Comment by lukaszlenart** [comment]
@sa-ChristianNiessner you are free to go with this :)

**Comment by sa-ChristianNiessner** [comment]
And here it is. Just got the mails about the 3.1.5 release ;)

**Comment by lukaszlenart** [comment]
I see no objections, merge party!

**Comment by lukaszlenart** [comment]
Fixed by merging #26
