### ISSUE TITLE
capitalizeBeanPropertyName

### ISSUE THREAD

**Issue by shimanshe** [jkuhnert/ognl#27]
Hi,
in class OnglRuntime, method capitalizeBeanPropertyName
the code:
 char first = propertyName.charAt(0);
    char second = propertyName.charAt(1);
    if ((Character.isLowerCase(first)) && (Character.isUpperCase(second))) {
      return propertyName;
    }
    char[] chars = propertyName.toCharArray();
    chars[0] = Character.toUpperCase(chars[0]);

when i define a field name "iType" and setter method setIType(eclipse automatic generated setter method), then capitalizeBeanPropertyName method return "iType", this results method "_getSetMethod" cann't find the setter method for "iType".
    the further infuence, struts2 2.3.28 reference the ongl library 3.0.14, when I defined a field the name such as "iType" in a Action class, the i can't auto inject the request parameter for "iType".
I find the ognl version "3.0.6" has not the problem. I find this issue just when i upgrade struts2 from version 2.3.15 to 2.3.28. 
Please check the problem if it exists, Thanks in advance!

**Comment by lukaszlenart** [comment]
OGNL as from 3.0.8 follows JavaBean Specification, see `8.8 Capitalization of inferred names` chapter, here you can find more details: https://issues.apache.org/jira/browse/WW-3909
