### ISSUE TITLE
Negative number is considered an arithmetic expression

### ISSUE THREAD

**Issue by lenggi** [jkuhnert/ognl#28]
With the newly introduced check for arithmetic expressions, negative numbers are considered to be arithmetic expressions.

I can understand that one does not want to have arithmetic expressions in parameter names. OTOH, I would not consider a negative number as an arithmetic expression.

Note that this has also been reported to the struts2 project under https://issues.apache.org/jira/browse/WW-4651

@lukaszlenart asked me to post this here as well.

**Comment by lukaszlenart** [comment]
Fixed in 3.1.10 & 3.0.19
