### ISSUE TITLE
Ognl.GetMethods does not return default methods from interfaces implemented by parent class

### ISSUE THREAD

**Issue by vlastimil-dolejs** [jkuhnert/ognl#29]
Same problem as here: https://issues.apache.org/jira/browse/OGNL-249
But fix for issue 249 takes into account only interfaces directly implemented by a class and not an interfaces implemented by a parent classes.
I will prepare a pull request with a test case (and maybe a fix also)

**Comment by lukaszlenart** [comment]
PR #30 merged
