### ISSUE TITLE
"hashCode()" being called when accessing a "code" field

### ISSUE THREAD

**Issue by danielfernandez** [jkuhnert/ognl#32]
If we have a public `code` field in a class, such as:
```java
public class Something {
   public String code = "abc123";
}
```
And, being `s` an object of type `Something`, we execute this expression:
```
s.code
```
Instead of returning `"abc123"`, the hash code will be returned because the `hashCode()` method will be selected for execution.

The responsible for this is this block of code in `OgnlRuntime`: https://github.com/jkuhnert/ognl/blob/751084b4802b488e0386ab702e230cceca296254/src/java/ognl/OgnlRuntime.java#L2947-L2954
```java
if (methods[i].getName().toLowerCase().endsWith(name)
    && !methods[i].getName().startsWith("set")
    && methods[i].getMethod().getReturnType() != Void.TYPE) {

    Method m = methods[i].getMethod();
    if (!candidates.contains(m))
        candidates.add(m);
}
```
IMHO the check applied here is far too lenient, especially given the fact that field names have not  been checked yet by the time this executes…

**Comment by danielfernandez** [comment]
This is the cause of thymeleaf/thymeleaf#546

**Comment by lukaszlenart** [comment]
Yeah... but a public field isn't something normal in Java ecosystem...

**Comment by danielfernandez** [comment]
Fixed. All tests pass. Thanks!
