### ISSUE TITLE
Output in System.err 'Two methods with same method signature but not providing classes assignable?'

### ISSUE THREAD

**Issue by harawata** [jkuhnert/ognl#35]
Here is a repro:

```java
  @Test
  public void test() throws Exception {
    String expressiosn = "list.isEmpty()";
    Object expr = Ognl.parseExpression(expressiosn);
    OgnlContext ctx = new OgnlContext();
    List<String> list = Collections.singletonList("string");
    ctx.put("list", list);
    Object value = Ognl.getValue(expr, ctx);
    Assert.assertFalse((Boolean)value);
  }
```

The above test passes, but the following message is output in System.err.

> Two methods with same method signature but not providing classes assignable? "public abstract boolean java.util.List.isEmpty()" and "public boolean java.util.AbstractCollection.isEmpty()" please report!

- The line that outputs the message is [here](https://github.com/jkuhnert/ognl/blob/7f6ebaf06b0e00630902b95ed18f9fccde27f0d9/src/java/ognl/OgnlRuntime.java#L1393).
- This seems to be a side effect of ca37319fb74ad8468acc78db5d3ba9d7b4863765 .

This was reported on [MyBatis tracker](https://github.com/mybatis/mybatis-3/issues/929) a while ago.

**Comment by lukaszlenart** [comment]
To be honest ... I have no idea how to fix that and I think the original authors also didn't take into account that the interfaces could have a real methods some day ...

**Comment by lukaszlenart** [comment]
The only idea I have is to remove this warning ... right now it's a valid case :)

**Comment by PatrickGotthard** [comment]
It is possible to check whether a method is a default method. Maybe it is possible to add this check to the code.

**Comment by lukaszlenart** [comment]
but not when using JDK7 as a source target.

**Comment by PatrickGotthard** [comment]
Hi Lukasz,

you're absolute right. Maybe using a logging framework instead of System.err is also an option?

Regards,
Patrick
