### ISSUE TITLE
OgnlContext(Map) construct always throws exception

### ISSUE THREAD

**Issue by lawley** [jkuhnert/ognl#37]
In this commit https://github.com/jkuhnert/ognl/commit/e30b2112979d1be7bed8073f1f47bffed6277fb2 `OgnlContext(MemberAccess memberAccess, ClassResolver classResolver, TypeConverter typeConverter, Map values)` was updates to throw an exception if `memberAccess` is `null`.

The constructor `OgnlContext(Map values)` always passes null and thus cannot ever work.

This impacts Thymeleaf since it calls `OgnlContext(Map values)` from its OGNL expression code.

**Comment by lukaszlenart** [comment]
You are using [unstable](https://github.com/jkuhnert/ognl#release-notes---version-322---wip-new-changes-are-coming) release, also those changes were introduced to improve security.

I would rather change Thymeleaf to use a proper constructor of `OgnlContext` instead.

**Comment by cesarhernandezgt** [comment]
Now that 3.2.3 was released.

Where can I find an example of the proper way to create and use the `memberAccess`  in a proper `OgnlContext`? 

I looked at http://commons.apache.org/proper/commons-ognl/developer-guide.html but didn't find a clear example.

**Comment by lukaszlenart** [comment]
It was released but it is still WIP :)

The simplest way is to implement your own `AccessMember` based on the [DefaultAccessMember](https://github.com/jkuhnert/ognl/blob/master/src/test/java/ognl/DefaultMemberAccess.java) and create context like this

```java
Ognl.createDefaultContext(root, new MyMemberAccess())
````
