### ISSUE TITLE
Is correct DefaultMemberAccess#setup?

### ISSUE THREAD

**Issue by kazuki43zoo** [jkuhnert/ognl#47]
Is correct following code?

https://github.com/jkuhnert/ognl/blob/0ca96030e40600892ea8b1548bbe275548ea1d48/src/test/java/ognl/DefaultMemberAccess.java#L114

Should be set the `Boolean.FALSE` in this case?
WDYT?

**Comment by lukaszlenart** [comment]
Yeah, looks like. Good 👁 :)

**Comment by kazuki43zoo** [comment]
merged into master and 3.1.x branches.
