### ISSUE TITLE
MemberAccess support private static method and private field, but do not support private static field.

### ISSUE THREAD

**Issue by hengyunabc** [jkuhnert/ognl#58]
MemberAccess support private static method and private field, but do not support private static field.

Demo:

```java
import java.lang.reflect.AccessibleObject;
import java.lang.reflect.Member;
import java.lang.reflect.Modifier;
import java.util.Map;

import ognl.ClassResolver;
import ognl.MemberAccess;
import ognl.Ognl;
import ognl.OgnlContext;
import ognl.OgnlException;

public class MyDemo {

	private static String statidField = "fff";

	private String privateField = "ppp";

	private static String staticFunc() {
		return "static func";
	}

	private static MyDemo newInstance() {
		return new MyDemo();
	}

	public static void main(String[] args) throws OgnlException {
		OgnlContext context = new OgnlContext(new ClassResolver() {
			@Override
			public Class classForName(String className, Map context) throws ClassNotFoundException {
				return Class.forName(className);
			}

		}, null, new DefaultMemberAccess(true));

		context.setTraceEvaluations(true);

		Object root = null;

		System.out.println(Ognl.getValue("@MyDemo@staticFunc()", context, root));
		System.out.println(Ognl.getValue("@MyDemo@newInstance().privateField", context, root));
		// exception
		System.out.println(Ognl.getValue("@MyDemo@statidField", context, root));
	}

	public static class DefaultMemberAccess implements MemberAccess {
		public boolean allowPrivateAccess = false;
		public boolean allowProtectedAccess = false;
		public boolean allowPackageProtectedAccess = false;

		/*
		 * ===================================================================
		 * Constructors
		 * ===================================================================
		 */
		public DefaultMemberAccess(boolean allowAllAccess) {
			this(allowAllAccess, allowAllAccess, allowAllAccess);
		}

		public DefaultMemberAccess(boolean allowPrivateAccess, boolean allowProtectedAccess,
				boolean allowPackageProtectedAccess) {
			super();
			this.allowPrivateAccess = allowPrivateAccess;
			this.allowProtectedAccess = allowProtectedAccess;
			this.allowPackageProtectedAccess = allowPackageProtectedAccess;
		}

		/*
		 * =================================================================== Public
		 * methods ===================================================================
		 */
		public boolean getAllowPrivateAccess() {
			return allowPrivateAccess;
		}

		public void setAllowPrivateAccess(boolean value) {
			allowPrivateAccess = value;
		}

		public boolean getAllowProtectedAccess() {
			return allowProtectedAccess;
		}

		public void setAllowProtectedAccess(boolean value) {
			allowProtectedAccess = value;
		}

		public boolean getAllowPackageProtectedAccess() {
			return allowPackageProtectedAccess;
		}

		public void setAllowPackageProtectedAccess(boolean value) {
			allowPackageProtectedAccess = value;
		}

		/*
		 * ===================================================================
		 * MemberAccess interface
		 * ===================================================================
		 */
		public Object setup(Map context, Object target, Member member, String propertyName) {
			Object result = null;

			if (isAccessible(context, target, member, propertyName)) {
				AccessibleObject accessible = (AccessibleObject) member;

				if (!accessible.isAccessible()) {
					result = Boolean.TRUE;
					accessible.setAccessible(true);
				}
			}
			return result;
		}

		public void restore(Map context, Object target, Member member, String propertyName, Object state) {
			if (state != null) {
				((AccessibleObject) member).setAccessible(((Boolean) state).booleanValue());
			}
		}

		/**
		 * Returns true if the given member is accessible or can be made accessible by
		 * this object.
		 */
		public boolean isAccessible(Map context, Object target, Member member, String propertyName) {
			int modifiers = member.getModifiers();
			boolean result = Modifier.isPublic(modifiers);

			if (!result) {
				if (Modifier.isPrivate(modifiers)) {
					result = getAllowPrivateAccess();
				} else {
					if (Modifier.isProtected(modifiers)) {
						result = getAllowProtectedAccess();
					} else {
						result = getAllowPackageProtectedAccess();
					}
				}
			}
			return result;
		}
	}
}
```

Output:

```
static func
ppp
Exception in thread "main" ognl.OgnlException: Could not get static field statidField from class MyDemo [java.lang.NoSuchFieldException: statidField]
	at ognl.ASTStaticField.isNodeConstant(ASTStaticField.java:108)
	at ognl.SimpleNode.isConstant(SimpleNode.java:325)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:202)
	at ognl.SimpleNode.getValue(SimpleNode.java:236)
	at ognl.Ognl.getValue(Ognl.java:493)
	at ognl.Ognl.getValue(Ognl.java:595)
	at ognl.Ognl.getValue(Ognl.java:565)
	at MyDemo.main(MyDemo.java:42)
Caused by: java.lang.NoSuchFieldException: statidField
	at java.lang.Class.getField(Class.java:1703)
	at ognl.ASTStaticField.isNodeConstant(ASTStaticField.java:92)
	... 7 more
/-- Encapsulated exception ------------\
java.lang.NoSuchFieldException: statidField
	at java.lang.Class.getField(Class.java:1703)
	at ognl.ASTStaticField.isNodeConstant(ASTStaticField.java:92)
	at ognl.SimpleNode.isConstant(SimpleNode.java:325)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:202)
	at ognl.SimpleNode.getValue(SimpleNode.java:236)
	at ognl.Ognl.getValue(Ognl.java:493)
	at ognl.Ognl.getValue(Ognl.java:595)
	at ognl.Ognl.getValue(Ognl.java:565)
	at MyDemo.main(MyDemo.java:42)
\--------------------------------------/

```

**Comment by lukaszlenart** [comment]
`MemberAccess` is an interface, your implementation doesn't support private static fields. Just changed and everything will be ok :)

**Comment by hengyunabc** [comment]
@lukaszlenart 

I just `return true` in `MyDemo.DefaultMemberAccess.isAccessible(Map, Object, Member, String)`, but still do not work.

It seems that `MemberAccess` is not be invoked when access static field.

**Comment by lukaszlenart** [comment]
Ach.. you are right :)

**Comment by lukaszlenart** [comment]
Closed by #59 & #60

**Comment by lukaszlenart** [comment]
@hengyunabc we have encountered a [problem](https://issues.apache.org/jira/browse/WW-5004) with your change, do you have a use case why do you want to secure access to static fields?

**Comment by aleksandr-m** [comment]
Please note that this also affects `public static` fields. And calling `MemberAccess` can be expensive in some cases.

**Comment by hengyunabc** [comment]
> @hengyunabc we have encountered a [problem](https://issues.apache.org/jira/browse/WW-5004) with your change, do you have a use case why do you want to secure access to static fields?

We use `ognl` in Arthas, a Java Diagnostic Tool: https://github.com/alibaba/arthas.

In Arthas, the user can use `ognl` expression to print the Java Object. like :

```
$ ognl '@demo.MathGame@random'
```

```java
public class MathGame {
    private static Random random = new Random();
```

https://github.com/alibaba/arthas/blob/master/demo/src/main/java/demo/MathGame.java#L9

In Arthas, we hope that the user can access all the fields:

```java
public class OgnlExpress implements Express {
    private static final MemberAccess MEMBER_ACCESS = new DefaultMemberAccess(true);
```

https://github.com/alibaba/arthas/blob/master/core/src/main/java/com/taobao/arthas/core/command/express/OgnlExpress.java#L17

**Comment by lukaszlenart** [comment]
Did you have problems with accessing static fields before the change? The only thing that has changed was usage of `AccessMember` in accessing static fields, support for private fields was already there.

**Comment by hengyunabc** [comment]
> Did you have problems with accessing static fields before the change? The only thing that has changed was usage of `AccessMember` in accessing static fields, support for private fields was already there.

Before the change, can not access `private static` field.
In the `MyDemo` above, `ongl` throw exception `java.lang.NoSuchFieldException: statidField`.

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello @hengyunabc .

Is it possible for _Arthas_ to use/switch to the OGNL 3.2.x line ?  

That could potentially allow for a partial reversion of changes in the OGNL 3.1.x line, to mitigate the issue(s) that @lukaszlenart  and @aleksandr-m have commented on above,

For the OGNL 3.2.x line (and maybe 3.1.x) perhaps the feature/change you introduced could be made optional (revert to the original behaviour by default, and have an "opt-in" to allow access to `private static` fields).

I'd be willing to try putting together a change to achieve one or both of the above if people think there's any merit in such a plan.

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello @hengyunabc , @aleksandr-m  and @lukaszlenart .

I've put together a recent PR (#67) that _attempts to restore the original OGNL 3.1.x behaviour for public static fields_ (the default), while allowing for an opt-in for the feature that was introduced with @hengyunabc 's change.

I think that it should remain OK to access public static fields without access checks (as per the old behaviour), but the opt-in still requires access checks for non-public fields.

Do you think that the PR's strategy (or something along its lines) will "do the trick" ?

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello again.
After a comment raising concern over introducing an opt-in flag, the PR was updated to try for a compromise between the original behaviour (public static fields accessible without checks) and the new feature (non-public static fields accessible, but only if they pass the accessibility checks).
Using this strategy the next OGNL 3.1.x build could be effectively drop-in compatible for versions <= 3.1.18 as well as 3.1.19-3.1.21, without the need for a control flag.
