### ISSUE TITLE
OGNLContext deprecated constructor crashes

### ISSUE THREAD

**Issue by deved65** [jkuhnert/ognl#81]
In current release 3.2.11 and master the deprecated constructor  `public OgnlContext(Map values)` in line 117 is unusable and should be removed immediately (or fixed). Currently it will always leads to a NullPointerException in line 170 of the class.  To my understanding functionality marked with 'deprecated' should no longer be used (as it will be removed in a future release), but should not be unusable 'by concept'.

**Comment by lukaszlenart** [comment]
Are you sure it's about the [line 170](https://github.com/jkuhnert/ognl/blob/master/src/main/java/ognl/OgnlContext.java#L170)?

**Comment by deved65** [comment]
Sorry, I messed it up. It is [line 140](https://github.com/jkuhnert/ognl/blob/888b193f951c854f1acfd0d236bd1592f9632a17/src/main/java/ognl/OgnlContext.java#L120) with a RuntimeException. In [line 120 ](https://github.com/jkuhnert/ognl/blob/888b193f951c854f1acfd0d236bd1592f9632a17/src/main/java/ognl/OgnlContext.java#L140) the extensive [constructor](https://github.com/jkuhnert/ognl/blob/888b193f951c854f1acfd0d236bd1592f9632a17/src/main/java/ognl/OgnlContext.java#L123) is invoked with null reference for parameter `memberAccess`. In line 137 is a null reference check on memberAccess which in turn always must lead to the RuntimeException.

**Comment by lukaszlenart** [comment]
The best option I see is to drop that constructor..

**Comment by deved65** [comment]
If no meaningful or 'cheap' default implementation for MemberAccess can be provided I tend to agree.

**Comment by lukaszlenart** [comment]
Yeah... that's why I have removed the default implementation from the main code and moved it into tests - it was quite often used to replace a framework's specific implementation by hackers. And that's why OGNL 3.2.x requires to provide your own implementation, even as a copy of the default one based on the one used in tests.

**Comment by lukaszlenart** [comment]
Also please be aware that 3.2.x line is still a [work-in-progress](https://github.com/jkuhnert/ognl/blob/master/docs/VersionNotes.md#release-notes---version-323---wip-new-changes-are-coming) - maybe I should express that better

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi.

Dropping the single-argument constructor: https://github.com/jkuhnert/ognl/blob/6de4049f093eb643332bbf14090006fac516393c/src/main/java/ognl/OgnlContext.java#L121 that will now always fail with an exception seems reasonable to me.

At the same time, would it be beneficial to replace the generic RuntimeException exception: https://github.com/jkuhnert/ognl/blob/6de4049f093eb643332bbf14090006fac516393c/src/main/java/ognl/OgnlContext.java#L144
with a more  specific IllegalArgumentException instead ?

The updated exception could be something like:
```
throw new IllegalArgumentException("MemberAccess implementation must be provided - null not permitted!");
```

**Comment by lukaszlenart** [comment]
Good idea, if no objections let's do it :)

**Comment by lukaszlenart** [comment]
OGNL 3.2.14 is out
