### ISSUE TITLE
Updating from 3.1.X to 3.2.X breaks

### ISSUE THREAD

**Issue by SElab2019** [jkuhnert/ognl#97]
When I try to upgrade objectify from 3.1.X to 3.2.X. The following code breaks.
```
public class Demo {

	public void test() {

		OgnlContext ctx = new OgnlContext();

	}
}
```
The code should pass, but it throws an error:
```
Demo.java:[11,20] error: no suitable constructor found for OgnlContext(no arguments)
```

**Comment by lukaszlenart** [comment]
That's why it is `3.2.x`

**Comment by SElab2019** [comment]
Hi @lukaszlenart , thanks for your helping.  Yes, would it be better to add a breaking announcement in the release note? Then all other developers who use ognl can know it.

**Comment by lukaszlenart** [comment]
Is [this](https://github.com/jkuhnert/ognl/blob/master/docs/VersionNotes.md#release-notes---version-323---wip-new-changes-are-coming) enough?

**Comment by SElab2019** [comment]
Yes. Thanks for your conformation and fix.
